angular.module('app').controller('app_qwertqwertyuiuytrewqwertyuytrewqertyuytrewqwertyuytrewertyuytrewertyuiuytrertyuioiuytrertyuioiuytrertyuioiuytrertyuiouytrertyuiuytrertyuiuytrertyuiuytrertyuiuytr6667', app_qwertqwertyuiuytrewqwertyuytrewqertyuytrewqwertyuytrewertyuytrewertyuiuytrertyuioiuytrertyuioiuytrertyuioiuytrertyuiouytrertyuiuytrertyuiuytrertyuiuytrertyuiuytr6667);
function app_qwertqwertyuiuytrewqwertyuytrewqertyuytrewqwertyuytrewertyuytrewertyuiuytrertyuioiuytrertyuioiuytrertyuioiuytrertyuiouytrertyuiuytrertyuiuytrertyuiuytrertyuiuytr6667($scope, app) {
    'use strict';
    app.init($scope);
}